### PR TITLE
Bug/non numeric property value

### PR DESCRIPTION
**Pull request by fivetran-reneeli**
Pull Request
**Are you a current Fivetran customer?** 

internal
**What change(s) does this PR introduce?** 

Create a new macro to cast data types in a warehouse-agnostic way

**Did you update the CHANGELOG?** 

- [ ] Yes
- not yet

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [x] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [x] Yes, Issue/Feature https://github.com/fivetran/dbt_klaviyo/issues/17
- [ ] No 

**How did you test the PR changes?** 

 

- [x] CircleCi  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Review by MisterClean — CHANGES_REQUESTED** [review]
I saw that the PR failed [ in CircleCI ](https://app.circleci.com/pipelines/github/fivetran/dbt_klaviyo/163/workflows/bb9e05e4-110f-4d27-ae1c-7b6ca836527b/jobs/171?invite=true#step-105-98) for Redshift, because it doesn't have a try_cast() function.

Heres a Redshift snippet inspired by @jthandy https://github.com/dbt-labs/redshift/blob/main/macros/try_cast.sql

```
{%- macro redshift__try_cast(field, type) -%}
{%- if type == 'numeric' -%}

    case
        when trim({{field}}) ~ '^(0|[1-9][0-9]*)$' then trim({{field}})
        else null
    end::{{type}}

{% else %}
    {{ exceptions.raise_compiler_error(
            "non-numeric datatypes are not currently supported") }}

{% endif %}
{%- endmacro -%}
```

**Comment by fivetran-joemarkiewicz** [comment]
Hey @MisterClean you read our mind! We were just discussing a similar solution this morning.

We also were discussing possibly leveraging the `nullif` function to clean the code a bit more, similar to how we handle it [in our Shopify package](https://github.com/fivetran/dbt_shopify/blob/f8de2874ee218453f9f741bfb04ea422a6a852a4/models/shopify__transactions.sql#L9). We'll give the options a try and thanks so much for helping collaborate on this fix with our team 😄

**Comment by fivetran-reneeli** [comment]
> @fivetran-reneeli Looks like Redshift doesn't have an `ifnull` function. [CircleCI failed on that function](https://app.circleci.com/pipelines/github/fivetran/dbt_klaviyo/164/workflows/31b34eb9-311c-4ff6-975b-756463a081f8/jobs/172?invite=true#step-105-99).
> 
> The `{{ try_cast }}` macro does that function already though. Can you try this?
> 
> ` , sum(case when lower(type) = '{{ rm | lower }}' then coalesce({{ try_cast("numeric_value", "numeric") }}, 0) else 0 end)`

Hey @MisterClean thanks for keeping an eye on this-- you're right, that `ifnull` is only needed for postgres so I'm moving it to the macro itself. Just need to add in some conditionals for cross-db datatype compatibility and we should be good to go

**Comment by MisterClean** [comment]
@fivetran-joemarkiewicz @fivetran-reneeli awesome thanks for developing this fix. Helpful for my reporting!

I wasn't aware of that `{{ dbt_utils.type_numeric() }}` function, but it seems like the combination of that & `nullif()` would provide the same functionality as this `try_cast` approach.

From a readability standpoint, the `try_cast` macro has a more evocative name IMO. It may be worth generalizing this macro across more datatypes in the [fivetran_utils](https://github.com/fivetran/dbt_fivetran_utils) package. Happy to chip in if you think this function can extend into other packages

**Comment by fivetran-joemarkiewicz** [comment]
Hi @MisterClean I just pushed changes to the branch we are working on within this PR and saw the error be resolved on my end. Would you be able to try the following version of the package on your end and let us know if the issue still persists?

```yml
##packages.yml
packages:
    - git: https://github.com/fivetran/dbt_klaviyo.git
      revision: bug/non-numeric-property-value
      warn-unpinned: false
```
If this does fix your issue, I will move the `try_cast` PR to the dbt_fivetran_utils package and merge the changes for the next release of this package. Let me know how this branch goes!

**Comment by MisterClean** [comment]
@fivetran-joemarkiewicz & @fivetran-reneeli well done! I'll try running this branch against our Klaviyo data and get back to you either tomorrow or the weekend

**Review by fivetran-reneeli — COMMENTED** [review]
Just updated the changelog, the rest looks good; ran locally and checks off!

**Comment by MisterClean** [comment]
@fivetran-joemarkiewicz @fivetran-reneeli 
Confirming that this branch successfully runs in our BigQuery 🎉 Thank you!

`dbt run --select +klaviyo__person_campaign_flow`

Result:
```22:40:48  Found 20 models, 31 tests, 0 snapshots, 0 analyses, 514 macros, 0 operations, 0 seed files, 6 sources, 0 exposures, 0 metrics
22:40:48  Concurrency: 4 threads (target='default')
22:42:33  Finished running 6 view models, 7 table models, 2 incremental models in 105.00s.
22:42:33  Completed successfully
22:42:33  Done. PASS=15 WARN=0 ERROR=0 SKIP=0 TOTAL=15```

**Pull request merged**
